/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Test.Api;
using System.Collections;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShowsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ShowsApiTests
    {
        private ShowsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ShowsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShowsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ShowsApi
            //Assert.IsInstanceOfType(typeof(ShowsApi), instance, "instance is a ShowsApi");
        }

        /// <summary>
        /// Test UploadShows
        /// </summary>
        [Test]
        public void UploadShowsTest()
        {
            string xColorPhoneSessionToken = ConfigUtils.loadConfig().XColorPhoneSessionToken;
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            string userId = ConfigUtils.loadConfig().Uid;
            string fileName = "show_example";

            System.IO.Stream videoFile = File.OpenRead("../../resource/video_file.mp4");
            System.IO.Stream audioFile = File.OpenRead("../../resource/audio_test.wav");
            System.IO.Stream imageFile = File.OpenRead("../../resource/image_test.jpg");
            var response = instance.UploadShows(xColorPhoneSessionToken, xColorPhoneSignature, userId, fileName, videoFile, audioFile, imageFile);
            Assert.IsInstanceOf<string>(response, "response is string");
        }

        /// <summary>
        /// Test GetUploadShows
        /// </summary>
        [Test]
        public void GetUploadShowsTest()
        {

            var response = getUploadShow();
            Assert.IsInstanceOf<InlineResponse200>(response, "response is InlineResponse200");
        }
        private InlineResponse200 getUploadShow()
        {
            UploadShowsTest();
            string xColorPhoneSessionToken = ConfigUtils.loadConfig().XColorPhoneSessionToken;
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            string userId = ConfigUtils.loadConfig().Uid;
            Requestbody1 requestbody = new Requestbody1();
            requestbody.PerPage = 10;
            requestbody.PageIndex = 1;

            return instance.GetUploadShows(xColorPhoneSessionToken, xColorPhoneSignature, userId, requestbody);
        }

        /// <summary>
        /// Test DeleteUploadShows
        /// </summary>
        [Test]
        public void DeleteUploadShowsTest()
        {
            InlineResponse200 inlineResponse200 = getUploadShow();

            string xColorPhoneSessionToken = ConfigUtils.loadConfig().XColorPhoneSessionToken;
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            string userId = ConfigUtils.loadConfig().Uid;
            ShowIdLists showIdList = new ShowIdLists();
            List<int?> list = new List<int?>();
            UPloadShowList uPloadShowList = inlineResponse200.ShowList.FirstOrDefault();
            list.Add(uPloadShowList.CustomizeShowId);
            showIdList.ShowIdList = list;
            var response = instance.DeleteUploadShows(xColorPhoneSessionToken, xColorPhoneSignature, userId, showIdList);
            Assert.IsInstanceOf<string>(response, "response is string");
        }

        /// <summary>
        /// Test GetReviewedUploadShows
        /// </summary>
        [Test]
        public void GetReviewedUploadShowsTest()
        {
            string xColorPhoneSessionToken = ConfigUtils.loadConfig().XColorPhoneSessionToken;
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            string userId = ConfigUtils.loadConfig().Uid;
            Requestbody2 requestbody = new Requestbody2();
            requestbody.PageIndex = 1;
            requestbody.PerPage = 10;
            var response = instance.GetReviewedUploadShows(xColorPhoneSessionToken, xColorPhoneSignature, userId, requestbody);
            Assert.IsInstanceOf<InlineResponse200>(response, "response is InlineResponse200");
        }






        /// <summary>
        /// Test GetShows
        /// </summary>
        [Test]
        public void GetShowsTest()
        {
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            Requestbody requestbody = new Requestbody();
            requestbody.PerPage = 10;
            requestbody.PageIndex = 1;
            var response = instance.GetShows(xColorPhoneSignature, requestbody);
            Assert.IsInstanceOf<ShowListResponse>(response, "response is ShowListResponse");
        }

    }

}
