/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using IO.Swagger.Test.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserApiTests
    {
        private UserApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserApi
            //Assert.IsInstanceOfType(typeof(UserApi), instance, "instance is a UserApi");
        }

        
        /// <summary>
        /// Test GetUserProfile
        /// </summary>
        [Test]
        public void GetUserProfileTest()
        {
            string xColorPhoneSessionToken = ConfigUtils.loadConfig().XColorPhoneSessionToken;
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            string userId = ConfigUtils.loadConfig().Uid;
            var response = instance.GetUserProfile(xColorPhoneSessionToken, xColorPhoneSignature, userId);
            Assert.IsInstanceOf<LoginResponse>(response, "response is LoginResponse");
        }
        
        /// <summary>
        /// Test PutUserProfile
        /// </summary>
        [Test]
        public void PutUserProfileTest()
        {
            string userId = ConfigUtils.loadConfig().Uid;
            string name = "CsharpTest";
            string gender = "man";
            string birthday = "2018-09-21";
            string signature = "signature is not null";
            System.IO.Stream headImage = File.OpenRead("../../resource/thumbnail.png");
            string xColorPhoneSessionToken = ConfigUtils.loadConfig().XColorPhoneSessionToken;
            string xColorPhoneSignature = ConfigUtils.loadConfig().XColorPhoneSignature;
            var response = instance.PutUserProfile(userId, name, gender, birthday, signature, headImage, xColorPhoneSessionToken, xColorPhoneSignature);
            Assert.IsInstanceOf<string>(response, "response is string");
        }
        
        /// <summary>
        /// Test Userlogin
        /// </summary>
        [Test]
        public void UserloginTest()
        {

            string xColorPhoneSignature = "12345678,87654321";
            LoginRequest body = new LoginRequest();
            body.LoginType = 1;
            Dictionary<string, Object> LoginInfo = new Dictionary<string, object>();
            body.LoginInfo = LoginInfo;
            LoginInfo.Add("wechat_code", "081NMnoV1uuV3Y0oG1nV1zxuoV1NMnog");
            var response = instance.Userlogin(xColorPhoneSignature, body);
            Assert.IsInstanceOf<LoginResponse>(response, "response is LoginResponse");



            var config = new Config()
            {

                Uid = response.UserInfo.UserId,
                XColorPhoneSessionToken = response.Token,
                XColorPhoneSignature = "12345678,87654321"
            };
            var serializer = new SerializerBuilder().Build();
            StreamWriter writer = new StreamWriter("../../resource/config.yaml");

            serializer.Serialize(writer, config);
            writer.Flush();

        }

    }

}
