/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// LocalPush
    /// </summary>
    [DataContract]
    public partial class LocalPush :  IEquatable<LocalPush>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalPush" /> class.
        /// </summary>
        /// <param name="enable">enable.</param>
        /// <param name="localPushIcon">localPushIcon.</param>
        /// <param name="localPushPreviewImage">localPushPreviewImage.</param>
        public LocalPush(bool? enable = default(bool?), string localPushIcon = default(string), string localPushPreviewImage = default(string))
        {
            this.Enable = enable;
            this.LocalPushIcon = localPushIcon;
            this.LocalPushPreviewImage = localPushPreviewImage;
        }
        
        /// <summary>
        /// Gets or Sets Enable
        /// </summary>
        [DataMember(Name="Enable", EmitDefaultValue=false)]
        public bool? Enable { get; set; }

        /// <summary>
        /// Gets or Sets LocalPushIcon
        /// </summary>
        [DataMember(Name="LocalPushIcon", EmitDefaultValue=false)]
        public string LocalPushIcon { get; set; }

        /// <summary>
        /// Gets or Sets LocalPushPreviewImage
        /// </summary>
        [DataMember(Name="LocalPushPreviewImage", EmitDefaultValue=false)]
        public string LocalPushPreviewImage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LocalPush {\n");
            sb.Append("  Enable: ").Append(Enable).Append("\n");
            sb.Append("  LocalPushIcon: ").Append(LocalPushIcon).Append("\n");
            sb.Append("  LocalPushPreviewImage: ").Append(LocalPushPreviewImage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LocalPush);
        }

        /// <summary>
        /// Returns true if LocalPush instances are equal
        /// </summary>
        /// <param name="input">Instance of LocalPush to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LocalPush input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Enable == input.Enable ||
                    (this.Enable != null &&
                    this.Enable.Equals(input.Enable))
                ) && 
                (
                    this.LocalPushIcon == input.LocalPushIcon ||
                    (this.LocalPushIcon != null &&
                    this.LocalPushIcon.Equals(input.LocalPushIcon))
                ) && 
                (
                    this.LocalPushPreviewImage == input.LocalPushPreviewImage ||
                    (this.LocalPushPreviewImage != null &&
                    this.LocalPushPreviewImage.Equals(input.LocalPushPreviewImage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Enable != null)
                    hashCode = hashCode * 59 + this.Enable.GetHashCode();
                if (this.LocalPushIcon != null)
                    hashCode = hashCode * 59 + this.LocalPushIcon.GetHashCode();
                if (this.LocalPushPreviewImage != null)
                    hashCode = hashCode * 59 + this.LocalPushPreviewImage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
