/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// LoginRequest
    /// </summary>
    [DataContract]
    public partial class LoginRequest :  IEquatable<LoginRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginRequest" /> class.
        /// </summary>
        /// <param name="loginType">loginType.</param>
        /// <param name="loginInfo">loginInfo.</param>
        public LoginRequest(int? loginType = default(int?), Dictionary<string, Object> loginInfo = default(Dictionary<string, Object>))
        {
            this.LoginType = loginType;
            this.LoginInfo = loginInfo;
        }
        
        /// <summary>
        /// Gets or Sets LoginType
        /// </summary>
        [DataMember(Name="login_type", EmitDefaultValue=false)]
        public int? LoginType { get; set; }

        /// <summary>
        /// Gets or Sets LoginInfo
        /// </summary>
        [DataMember(Name="login_info", EmitDefaultValue=false)]
        public Dictionary<string, Object> LoginInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoginRequest {\n");
            sb.Append("  LoginType: ").Append(LoginType).Append("\n");
            sb.Append("  LoginInfo: ").Append(LoginInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LoginRequest);
        }

        /// <summary>
        /// Returns true if LoginRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of LoginRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoginRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoginType == input.LoginType ||
                    (this.LoginType != null &&
                    this.LoginType.Equals(input.LoginType))
                ) && 
                (
                    this.LoginInfo == input.LoginInfo ||
                    this.LoginInfo != null &&
                    this.LoginInfo.SequenceEqual(input.LoginInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoginType != null)
                    hashCode = hashCode * 59 + this.LoginType.GetHashCode();
                if (this.LoginInfo != null)
                    hashCode = hashCode * 59 + this.LoginInfo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
