/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ShowList
    /// </summary>
    [DataContract]
    public partial class ShowList :  IEquatable<ShowList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShowList" /> class.
        /// </summary>
        /// <param name="description">description.</param>
        /// <param name="downloadNum">downloadNum.</param>
        /// <param name="gif">gif.</param>
        /// <param name="hot">hot.</param>
        /// <param name="showId">showId.</param>
        /// <param name="icon">icon.</param>
        /// <param name="iconAccept">iconAccept.</param>
        /// <param name="iconReject">iconReject.</param>
        /// <param name="id">id.</param>
        /// <param name="idName">idName.</param>
        /// <param name="localPush">localPush.</param>
        /// <param name="mp4">mp4.</param>
        /// <param name="name">name.</param>
        /// <param name="previewImage">previewImage.</param>
        /// <param name="resType">resType.</param>
        /// <param name="userName">userName.</param>
        /// <param name="ringtone">ringtone.</param>
        /// <param name="themeGuidePreviewImage">themeGuidePreviewImage.</param>
        /// <param name="status">status.</param>
        public ShowList(string description = default(string), int? downloadNum = default(int?), string gif = default(string), bool? hot = default(bool?), int? showId = default(int?), string icon = default(string), string iconAccept = default(string), string iconReject = default(string), int? id = default(int?), string idName = default(string), LocalPush localPush = default(LocalPush), string mp4 = default(string), string name = default(string), string previewImage = default(string), string resType = default(string), string userName = default(string), string ringtone = default(string), string themeGuidePreviewImage = default(string), Status status = default(Status))
        {
            this.Description = description;
            this.DownloadNum = downloadNum;
            this.Gif = gif;
            this.Hot = hot;
            this.ShowId = showId;
            this.Icon = icon;
            this.IconAccept = iconAccept;
            this.IconReject = iconReject;
            this.Id = id;
            this.IdName = idName;
            this.LocalPush = localPush;
            this.Mp4 = mp4;
            this.Name = name;
            this.PreviewImage = previewImage;
            this.ResType = resType;
            this.UserName = userName;
            this.Ringtone = ringtone;
            this.ThemeGuidePreviewImage = themeGuidePreviewImage;
            this.Status = status;
        }
        
        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets DownloadNum
        /// </summary>
        [DataMember(Name="download_num", EmitDefaultValue=false)]
        public int? DownloadNum { get; set; }

        /// <summary>
        /// Gets or Sets Gif
        /// </summary>
        [DataMember(Name="gif", EmitDefaultValue=false)]
        public string Gif { get; set; }

        /// <summary>
        /// Gets or Sets Hot
        /// </summary>
        [DataMember(Name="hot", EmitDefaultValue=false)]
        public bool? Hot { get; set; }

        /// <summary>
        /// Gets or Sets ShowId
        /// </summary>
        [DataMember(Name="show_id", EmitDefaultValue=false)]
        public int? ShowId { get; set; }

        /// <summary>
        /// Gets or Sets Icon
        /// </summary>
        [DataMember(Name="icon", EmitDefaultValue=false)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets IconAccept
        /// </summary>
        [DataMember(Name="icon_accept", EmitDefaultValue=false)]
        public string IconAccept { get; set; }

        /// <summary>
        /// Gets or Sets IconReject
        /// </summary>
        [DataMember(Name="icon_reject", EmitDefaultValue=false)]
        public string IconReject { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets IdName
        /// </summary>
        [DataMember(Name="id_name", EmitDefaultValue=false)]
        public string IdName { get; set; }

        /// <summary>
        /// Gets or Sets LocalPush
        /// </summary>
        [DataMember(Name="localPush", EmitDefaultValue=false)]
        public LocalPush LocalPush { get; set; }

        /// <summary>
        /// Gets or Sets Mp4
        /// </summary>
        [DataMember(Name="mp4", EmitDefaultValue=false)]
        public string Mp4 { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PreviewImage
        /// </summary>
        [DataMember(Name="preview_image", EmitDefaultValue=false)]
        public string PreviewImage { get; set; }

        /// <summary>
        /// Gets or Sets ResType
        /// </summary>
        [DataMember(Name="res_type", EmitDefaultValue=false)]
        public string ResType { get; set; }

        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [DataMember(Name="user_name", EmitDefaultValue=false)]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or Sets Ringtone
        /// </summary>
        [DataMember(Name="ringtone", EmitDefaultValue=false)]
        public string Ringtone { get; set; }

        /// <summary>
        /// Gets or Sets ThemeGuidePreviewImage
        /// </summary>
        [DataMember(Name="theme_guide_preview_image", EmitDefaultValue=false)]
        public string ThemeGuidePreviewImage { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public Status Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShowList {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DownloadNum: ").Append(DownloadNum).Append("\n");
            sb.Append("  Gif: ").Append(Gif).Append("\n");
            sb.Append("  Hot: ").Append(Hot).Append("\n");
            sb.Append("  ShowId: ").Append(ShowId).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  IconAccept: ").Append(IconAccept).Append("\n");
            sb.Append("  IconReject: ").Append(IconReject).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IdName: ").Append(IdName).Append("\n");
            sb.Append("  LocalPush: ").Append(LocalPush).Append("\n");
            sb.Append("  Mp4: ").Append(Mp4).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PreviewImage: ").Append(PreviewImage).Append("\n");
            sb.Append("  ResType: ").Append(ResType).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Ringtone: ").Append(Ringtone).Append("\n");
            sb.Append("  ThemeGuidePreviewImage: ").Append(ThemeGuidePreviewImage).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShowList);
        }

        /// <summary>
        /// Returns true if ShowList instances are equal
        /// </summary>
        /// <param name="input">Instance of ShowList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShowList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DownloadNum == input.DownloadNum ||
                    (this.DownloadNum != null &&
                    this.DownloadNum.Equals(input.DownloadNum))
                ) && 
                (
                    this.Gif == input.Gif ||
                    (this.Gif != null &&
                    this.Gif.Equals(input.Gif))
                ) && 
                (
                    this.Hot == input.Hot ||
                    (this.Hot != null &&
                    this.Hot.Equals(input.Hot))
                ) && 
                (
                    this.ShowId == input.ShowId ||
                    (this.ShowId != null &&
                    this.ShowId.Equals(input.ShowId))
                ) && 
                (
                    this.Icon == input.Icon ||
                    (this.Icon != null &&
                    this.Icon.Equals(input.Icon))
                ) && 
                (
                    this.IconAccept == input.IconAccept ||
                    (this.IconAccept != null &&
                    this.IconAccept.Equals(input.IconAccept))
                ) && 
                (
                    this.IconReject == input.IconReject ||
                    (this.IconReject != null &&
                    this.IconReject.Equals(input.IconReject))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.IdName == input.IdName ||
                    (this.IdName != null &&
                    this.IdName.Equals(input.IdName))
                ) && 
                (
                    this.LocalPush == input.LocalPush ||
                    (this.LocalPush != null &&
                    this.LocalPush.Equals(input.LocalPush))
                ) && 
                (
                    this.Mp4 == input.Mp4 ||
                    (this.Mp4 != null &&
                    this.Mp4.Equals(input.Mp4))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.PreviewImage == input.PreviewImage ||
                    (this.PreviewImage != null &&
                    this.PreviewImage.Equals(input.PreviewImage))
                ) && 
                (
                    this.ResType == input.ResType ||
                    (this.ResType != null &&
                    this.ResType.Equals(input.ResType))
                ) && 
                (
                    this.UserName == input.UserName ||
                    (this.UserName != null &&
                    this.UserName.Equals(input.UserName))
                ) && 
                (
                    this.Ringtone == input.Ringtone ||
                    (this.Ringtone != null &&
                    this.Ringtone.Equals(input.Ringtone))
                ) && 
                (
                    this.ThemeGuidePreviewImage == input.ThemeGuidePreviewImage ||
                    (this.ThemeGuidePreviewImage != null &&
                    this.ThemeGuidePreviewImage.Equals(input.ThemeGuidePreviewImage))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.DownloadNum != null)
                    hashCode = hashCode * 59 + this.DownloadNum.GetHashCode();
                if (this.Gif != null)
                    hashCode = hashCode * 59 + this.Gif.GetHashCode();
                if (this.Hot != null)
                    hashCode = hashCode * 59 + this.Hot.GetHashCode();
                if (this.ShowId != null)
                    hashCode = hashCode * 59 + this.ShowId.GetHashCode();
                if (this.Icon != null)
                    hashCode = hashCode * 59 + this.Icon.GetHashCode();
                if (this.IconAccept != null)
                    hashCode = hashCode * 59 + this.IconAccept.GetHashCode();
                if (this.IconReject != null)
                    hashCode = hashCode * 59 + this.IconReject.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.IdName != null)
                    hashCode = hashCode * 59 + this.IdName.GetHashCode();
                if (this.LocalPush != null)
                    hashCode = hashCode * 59 + this.LocalPush.GetHashCode();
                if (this.Mp4 != null)
                    hashCode = hashCode * 59 + this.Mp4.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.PreviewImage != null)
                    hashCode = hashCode * 59 + this.PreviewImage.GetHashCode();
                if (this.ResType != null)
                    hashCode = hashCode * 59 + this.ResType.GetHashCode();
                if (this.UserName != null)
                    hashCode = hashCode * 59 + this.UserName.GetHashCode();
                if (this.Ringtone != null)
                    hashCode = hashCode * 59 + this.Ringtone.GetHashCode();
                if (this.ThemeGuidePreviewImage != null)
                    hashCode = hashCode * 59 + this.ThemeGuidePreviewImage.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
