/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ShowIdLists
    /// </summary>
    [DataContract]
    public partial class ShowIdLists :  IEquatable<ShowIdLists>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShowIdLists" /> class.
        /// </summary>
        /// <param name="showIdList">showIdList.</param>
        public ShowIdLists(List<int?> showIdList = default(List<int?>))
        {
            this.ShowIdList = showIdList;
        }
        
        /// <summary>
        /// Gets or Sets ShowIdList
        /// </summary>
        [DataMember(Name="show_id_list", EmitDefaultValue=false)]
        public List<int?> ShowIdList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShowIdLists {\n");
            sb.Append("  ShowIdList: ").Append(ShowIdList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShowIdLists);
        }

        /// <summary>
        /// Returns true if ShowIdLists instances are equal
        /// </summary>
        /// <param name="input">Instance of ShowIdLists to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShowIdLists input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShowIdList == input.ShowIdList ||
                    this.ShowIdList != null &&
                    this.ShowIdList.SequenceEqual(input.ShowIdList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShowIdList != null)
                    hashCode = hashCode * 59 + this.ShowIdList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
