/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Status
    /// </summary>
    [DataContract]
    public partial class Status :  IEquatable<Status>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Status" /> class.
        /// </summary>
        /// <param name="_lock">_lock.</param>
        /// <param name="staticPreview">staticPreview.</param>
        public Status(bool? _lock = default(bool?), bool? staticPreview = default(bool?))
        {
            this.Lock = _lock;
            this.StaticPreview = staticPreview;
        }
        
        /// <summary>
        /// Gets or Sets Lock
        /// </summary>
        [DataMember(Name="Lock", EmitDefaultValue=false)]
        public bool? Lock { get; set; }

        /// <summary>
        /// Gets or Sets StaticPreview
        /// </summary>
        [DataMember(Name="StaticPreview", EmitDefaultValue=false)]
        public bool? StaticPreview { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Status {\n");
            sb.Append("  Lock: ").Append(Lock).Append("\n");
            sb.Append("  StaticPreview: ").Append(StaticPreview).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Status);
        }

        /// <summary>
        /// Returns true if Status instances are equal
        /// </summary>
        /// <param name="input">Instance of Status to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Status input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Lock == input.Lock ||
                    (this.Lock != null &&
                    this.Lock.Equals(input.Lock))
                ) && 
                (
                    this.StaticPreview == input.StaticPreview ||
                    (this.StaticPreview != null &&
                    this.StaticPreview.Equals(input.StaticPreview))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Lock != null)
                    hashCode = hashCode * 59 + this.Lock.GetHashCode();
                if (this.StaticPreview != null)
                    hashCode = hashCode * 59 + this.StaticPreview.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
