/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LocalPush
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocalPushTests
    {
        // TODO uncomment below to declare an instance variable for LocalPush
        //private LocalPush instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocalPush
            //instance = new LocalPush();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocalPush
        /// </summary>
        [Test]
        public void LocalPushInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalPush
            //Assert.IsInstanceOfType<LocalPush> (instance, "variable 'instance' is a LocalPush");
        }


        /// <summary>
        /// Test the property 'Enable'
        /// </summary>
        [Test]
        public void EnableTest()
        {
            // TODO unit test for the property 'Enable'
        }
        /// <summary>
        /// Test the property 'LocalPushIcon'
        /// </summary>
        [Test]
        public void LocalPushIconTest()
        {
            // TODO unit test for the property 'LocalPushIcon'
        }
        /// <summary>
        /// Test the property 'LocalPushPreviewImage'
        /// </summary>
        [Test]
        public void LocalPushPreviewImageTest()
        {
            // TODO unit test for the property 'LocalPushPreviewImage'
        }

    }

}
