/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoginResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginResponseTests
    {
        // TODO uncomment below to declare an instance variable for LoginResponse
        //private LoginResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginResponse
            //instance = new LoginResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginResponse
        /// </summary>
        [Test]
        public void LoginResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginResponse
            //Assert.IsInstanceOfType<LoginResponse> (instance, "variable 'instance' is a LoginResponse");
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UserInfo'
        /// </summary>
        [Test]
        public void UserInfoTest()
        {
            // TODO unit test for the property 'UserInfo'
        }

    }

}
