/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginRequestTests
    {
        // TODO uncomment below to declare an instance variable for LoginRequest
        //private LoginRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginRequest
            //instance = new LoginRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginRequest
        /// </summary>
        [Test]
        public void LoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginRequest
            //Assert.IsInstanceOfType<LoginRequest> (instance, "variable 'instance' is a LoginRequest");
        }


        /// <summary>
        /// Test the property 'LoginType'
        /// </summary>
        [Test]
        public void LoginTypeTest()
        {
            // TODO unit test for the property 'LoginType'
        }
        /// <summary>
        /// Test the property 'LoginInfo'
        /// </summary>
        [Test]
        public void LoginInfoTest()
        {
            // TODO unit test for the property 'LoginInfo'
        }

    }

}
