/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Requestbody1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Requestbody1Tests
    {
        // TODO uncomment below to declare an instance variable for Requestbody1
        //private Requestbody1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Requestbody1
            //instance = new Requestbody1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Requestbody1
        /// </summary>
        [Test]
        public void Requestbody1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Requestbody1
            //Assert.IsInstanceOfType<Requestbody1> (instance, "variable 'instance' is a Requestbody1");
        }


        /// <summary>
        /// Test the property 'PerPage'
        /// </summary>
        [Test]
        public void PerPageTest()
        {
            // TODO unit test for the property 'PerPage'
        }
        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Test]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

    }

}
