/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShowListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShowListResponseTests
    {
        // TODO uncomment below to declare an instance variable for ShowListResponse
        //private ShowListResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShowListResponse
            //instance = new ShowListResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShowListResponse
        /// </summary>
        [Test]
        public void ShowListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShowListResponse
            //Assert.IsInstanceOfType<ShowListResponse> (instance, "variable 'instance' is a ShowListResponse");
        }


        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Test]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }
        /// <summary>
        /// Test the property 'ShowList'
        /// </summary>
        [Test]
        public void ShowListTest()
        {
            // TODO unit test for the property 'ShowList'
        }

    }

}
