/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShowList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShowListTests
    {
        // TODO uncomment below to declare an instance variable for ShowList
        //private ShowList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShowList
            //instance = new ShowList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShowList
        /// </summary>
        [Test]
        public void ShowListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShowList
            //Assert.IsInstanceOfType<ShowList> (instance, "variable 'instance' is a ShowList");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DownloadNum'
        /// </summary>
        [Test]
        public void DownloadNumTest()
        {
            // TODO unit test for the property 'DownloadNum'
        }
        /// <summary>
        /// Test the property 'Gif'
        /// </summary>
        [Test]
        public void GifTest()
        {
            // TODO unit test for the property 'Gif'
        }
        /// <summary>
        /// Test the property 'Hot'
        /// </summary>
        [Test]
        public void HotTest()
        {
            // TODO unit test for the property 'Hot'
        }
        /// <summary>
        /// Test the property 'ShowId'
        /// </summary>
        [Test]
        public void ShowIdTest()
        {
            // TODO unit test for the property 'ShowId'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'IconAccept'
        /// </summary>
        [Test]
        public void IconAcceptTest()
        {
            // TODO unit test for the property 'IconAccept'
        }
        /// <summary>
        /// Test the property 'IconReject'
        /// </summary>
        [Test]
        public void IconRejectTest()
        {
            // TODO unit test for the property 'IconReject'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IdName'
        /// </summary>
        [Test]
        public void IdNameTest()
        {
            // TODO unit test for the property 'IdName'
        }
        /// <summary>
        /// Test the property 'LocalPush'
        /// </summary>
        [Test]
        public void LocalPushTest()
        {
            // TODO unit test for the property 'LocalPush'
        }
        /// <summary>
        /// Test the property 'Mp4'
        /// </summary>
        [Test]
        public void Mp4Test()
        {
            // TODO unit test for the property 'Mp4'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PreviewImage'
        /// </summary>
        [Test]
        public void PreviewImageTest()
        {
            // TODO unit test for the property 'PreviewImage'
        }
        /// <summary>
        /// Test the property 'ResType'
        /// </summary>
        [Test]
        public void ResTypeTest()
        {
            // TODO unit test for the property 'ResType'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'Ringtone'
        /// </summary>
        [Test]
        public void RingtoneTest()
        {
            // TODO unit test for the property 'Ringtone'
        }
        /// <summary>
        /// Test the property 'ThemeGuidePreviewImage'
        /// </summary>
        [Test]
        public void ThemeGuidePreviewImageTest()
        {
            // TODO unit test for the property 'ThemeGuidePreviewImage'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
