/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShowIdLists
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShowIdListsTests
    {
        // TODO uncomment below to declare an instance variable for ShowIdLists
        //private ShowIdLists instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShowIdLists
            //instance = new ShowIdLists();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShowIdLists
        /// </summary>
        [Test]
        public void ShowIdListsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShowIdLists
            //Assert.IsInstanceOfType<ShowIdLists> (instance, "variable 'instance' is a ShowIdLists");
        }


        /// <summary>
        /// Test the property 'ShowIdList'
        /// </summary>
        [Test]
        public void ShowIdListTest()
        {
            // TODO unit test for the property 'ShowIdList'
        }

    }

}
