/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UPloadShowList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UPloadShowListTests
    {
        // TODO uncomment below to declare an instance variable for UPloadShowList
        //private UPloadShowList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UPloadShowList
            //instance = new UPloadShowList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UPloadShowList
        /// </summary>
        [Test]
        public void UPloadShowListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UPloadShowList
            //Assert.IsInstanceOfType<UPloadShowList> (instance, "variable 'instance' is a UPloadShowList");
        }


        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'CustomizeShowId'
        /// </summary>
        [Test]
        public void CustomizeShowIdTest()
        {
            // TODO unit test for the property 'CustomizeShowId'
        }
        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Test]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Test]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'VideoUrl'
        /// </summary>
        [Test]
        public void VideoUrlTest()
        {
            // TODO unit test for the property 'VideoUrl'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Test]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'AudioUrl'
        /// </summary>
        [Test]
        public void AudioUrlTest()
        {
            // TODO unit test for the property 'AudioUrl'
        }

    }

}
