/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShowsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>string</returns>
        string DeleteUploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists);

        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> DeleteUploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists);
        /// <summary>
        /// get review shows
        /// </summary>
        /// <remarks>
        /// get review shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>InlineResponse200</returns>
        InlineResponse200 GetReviewedUploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody);

        /// <summary>
        /// get review shows
        /// </summary>
        /// <remarks>
        /// get review shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>ApiResponse of InlineResponse200</returns>
        ApiResponse<InlineResponse200> GetReviewedUploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody);
        /// <summary>
        /// shows
        /// </summary>
        /// <remarks>
        /// shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>ShowListResponse</returns>
        ShowListResponse GetShows (string xColorPhoneSignature, Requestbody requestbody);

        /// <summary>
        /// shows
        /// </summary>
        /// <remarks>
        /// shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>ApiResponse of ShowListResponse</returns>
        ApiResponse<ShowListResponse> GetShowsWithHttpInfo (string xColorPhoneSignature, Requestbody requestbody);
        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>InlineResponse200</returns>
        InlineResponse200 GetUploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody);

        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>ApiResponse of InlineResponse200</returns>
        ApiResponse<InlineResponse200> GetUploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody);
        /// <summary>
        /// upload shows
        /// </summary>
        /// <remarks>
        /// upload shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>string</returns>
        string UploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile);

        /// <summary>
        /// upload shows
        /// </summary>
        /// <remarks>
        /// upload shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> UploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> DeleteUploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists);

        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> DeleteUploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists);
        /// <summary>
        /// get review shows
        /// </summary>
        /// <remarks>
        /// get review shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of InlineResponse200</returns>
        System.Threading.Tasks.Task<InlineResponse200> GetReviewedUploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody);

        /// <summary>
        /// get review shows
        /// </summary>
        /// <remarks>
        /// get review shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ApiResponse (InlineResponse200)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse200>> GetReviewedUploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody);
        /// <summary>
        /// shows
        /// </summary>
        /// <remarks>
        /// shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ShowListResponse</returns>
        System.Threading.Tasks.Task<ShowListResponse> GetShowsAsync (string xColorPhoneSignature, Requestbody requestbody);

        /// <summary>
        /// shows
        /// </summary>
        /// <remarks>
        /// shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ApiResponse (ShowListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ShowListResponse>> GetShowsAsyncWithHttpInfo (string xColorPhoneSignature, Requestbody requestbody);
        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of InlineResponse200</returns>
        System.Threading.Tasks.Task<InlineResponse200> GetUploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody);

        /// <summary>
        /// get shows
        /// </summary>
        /// <remarks>
        /// get shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ApiResponse (InlineResponse200)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse200>> GetUploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody);
        /// <summary>
        /// upload shows
        /// </summary>
        /// <remarks>
        /// upload shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> UploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile);

        /// <summary>
        /// upload shows
        /// </summary>
        /// <remarks>
        /// upload shows
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> UploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ShowsApi : IShowsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ShowsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ShowsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShowsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ShowsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>string</returns>
        public string DeleteUploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists)
        {
             ApiResponse<string> localVarResponse = DeleteUploadShowsWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, showIdLists);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > DeleteUploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->DeleteUploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->DeleteUploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->DeleteUploadShows");
            // verify the required parameter 'showIdLists' is set
            if (showIdLists == null)
                throw new ApiException(400, "Missing required parameter 'showIdLists' when calling ShowsApi->DeleteUploadShows");

            var localVarPath = "/user/{user_id}/uploaded_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (showIdLists != null && showIdLists.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(showIdLists); // http body (model) parameter
            }
            else
            {
                localVarPostBody = showIdLists; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteUploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> DeleteUploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists)
        {
             ApiResponse<string> localVarResponse = await DeleteUploadShowsAsyncWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, showIdLists);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="showIdLists"></param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> DeleteUploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, ShowIdLists showIdLists)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->DeleteUploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->DeleteUploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->DeleteUploadShows");
            // verify the required parameter 'showIdLists' is set
            if (showIdLists == null)
                throw new ApiException(400, "Missing required parameter 'showIdLists' when calling ShowsApi->DeleteUploadShows");

            var localVarPath = "/user/{user_id}/uploaded_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (showIdLists != null && showIdLists.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(showIdLists); // http body (model) parameter
            }
            else
            {
                localVarPostBody = showIdLists; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteUploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// get review shows get review shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>InlineResponse200</returns>
        public InlineResponse200 GetReviewedUploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody)
        {
             ApiResponse<InlineResponse200> localVarResponse = GetReviewedUploadShowsWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, requestbody);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get review shows get review shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>ApiResponse of InlineResponse200</returns>
        public ApiResponse< InlineResponse200 > GetReviewedUploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->GetReviewedUploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->GetReviewedUploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->GetReviewedUploadShows");
            // verify the required parameter 'requestbody' is set
            if (requestbody == null)
                throw new ApiException(400, "Missing required parameter 'requestbody' when calling ShowsApi->GetReviewedUploadShows");

            var localVarPath = "/user/{user_id}/reviewed_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (requestbody != null && requestbody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestbody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestbody; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetReviewedUploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse200>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse200) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse200)));
        }

        /// <summary>
        /// get review shows get review shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of InlineResponse200</returns>
        public async System.Threading.Tasks.Task<InlineResponse200> GetReviewedUploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody)
        {
             ApiResponse<InlineResponse200> localVarResponse = await GetReviewedUploadShowsAsyncWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, requestbody);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get review shows get review shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ApiResponse (InlineResponse200)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse200>> GetReviewedUploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody2 requestbody)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->GetReviewedUploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->GetReviewedUploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->GetReviewedUploadShows");
            // verify the required parameter 'requestbody' is set
            if (requestbody == null)
                throw new ApiException(400, "Missing required parameter 'requestbody' when calling ShowsApi->GetReviewedUploadShows");

            var localVarPath = "/user/{user_id}/reviewed_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (requestbody != null && requestbody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestbody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestbody; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetReviewedUploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse200>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse200) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse200)));
        }

        /// <summary>
        /// shows shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>ShowListResponse</returns>
        public ShowListResponse GetShows (string xColorPhoneSignature, Requestbody requestbody)
        {
             ApiResponse<ShowListResponse> localVarResponse = GetShowsWithHttpInfo(xColorPhoneSignature, requestbody);
             return localVarResponse.Data;
        }

        /// <summary>
        /// shows shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>ApiResponse of ShowListResponse</returns>
        public ApiResponse< ShowListResponse > GetShowsWithHttpInfo (string xColorPhoneSignature, Requestbody requestbody)
        {
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->GetShows");
            // verify the required parameter 'requestbody' is set
            if (requestbody == null)
                throw new ApiException(400, "Missing required parameter 'requestbody' when calling ShowsApi->GetShows");

            var localVarPath = "/shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (requestbody != null && requestbody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestbody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestbody; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ShowListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ShowListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ShowListResponse)));
        }

        /// <summary>
        /// shows shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ShowListResponse</returns>
        public async System.Threading.Tasks.Task<ShowListResponse> GetShowsAsync (string xColorPhoneSignature, Requestbody requestbody)
        {
             ApiResponse<ShowListResponse> localVarResponse = await GetShowsAsyncWithHttpInfo(xColorPhoneSignature, requestbody);
             return localVarResponse.Data;

        }

        /// <summary>
        /// shows shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ApiResponse (ShowListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ShowListResponse>> GetShowsAsyncWithHttpInfo (string xColorPhoneSignature, Requestbody requestbody)
        {
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->GetShows");
            // verify the required parameter 'requestbody' is set
            if (requestbody == null)
                throw new ApiException(400, "Missing required parameter 'requestbody' when calling ShowsApi->GetShows");

            var localVarPath = "/shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (requestbody != null && requestbody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestbody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestbody; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ShowListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ShowListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ShowListResponse)));
        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>InlineResponse200</returns>
        public InlineResponse200 GetUploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody)
        {
             ApiResponse<InlineResponse200> localVarResponse = GetUploadShowsWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, requestbody);
             return localVarResponse.Data;
        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>ApiResponse of InlineResponse200</returns>
        public ApiResponse< InlineResponse200 > GetUploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->GetUploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->GetUploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->GetUploadShows");
            // verify the required parameter 'requestbody' is set
            if (requestbody == null)
                throw new ApiException(400, "Missing required parameter 'requestbody' when calling ShowsApi->GetUploadShows");

            var localVarPath = "/user/{user_id}/uploaded_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (requestbody != null && requestbody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestbody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestbody; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse200>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse200) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse200)));
        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of InlineResponse200</returns>
        public async System.Threading.Tasks.Task<InlineResponse200> GetUploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody)
        {
             ApiResponse<InlineResponse200> localVarResponse = await GetUploadShowsAsyncWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, requestbody);
             return localVarResponse.Data;

        }

        /// <summary>
        /// get shows get shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="requestbody"></param>
        /// <returns>Task of ApiResponse (InlineResponse200)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse200>> GetUploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, Requestbody1 requestbody)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->GetUploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->GetUploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->GetUploadShows");
            // verify the required parameter 'requestbody' is set
            if (requestbody == null)
                throw new ApiException(400, "Missing required parameter 'requestbody' when calling ShowsApi->GetUploadShows");

            var localVarPath = "/user/{user_id}/uploaded_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (requestbody != null && requestbody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestbody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestbody; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse200>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse200) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse200)));
        }

        /// <summary>
        /// upload shows upload shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>string</returns>
        public string UploadShows (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile)
        {
             ApiResponse<string> localVarResponse = UploadShowsWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, fileName, videoFile, audioFile, imageFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// upload shows upload shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > UploadShowsWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->UploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->UploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->UploadShows");
            // verify the required parameter 'fileName' is set
            if (fileName == null)
                throw new ApiException(400, "Missing required parameter 'fileName' when calling ShowsApi->UploadShows");
            // verify the required parameter 'videoFile' is set
            if (videoFile == null)
                throw new ApiException(400, "Missing required parameter 'videoFile' when calling ShowsApi->UploadShows");
            // verify the required parameter 'audioFile' is set
            if (audioFile == null)
                throw new ApiException(400, "Missing required parameter 'audioFile' when calling ShowsApi->UploadShows");
            // verify the required parameter 'imageFile' is set
            if (imageFile == null)
                throw new ApiException(400, "Missing required parameter 'imageFile' when calling ShowsApi->UploadShows");

            var localVarPath = "/user/{user_id}/uploaded_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (fileName != null) localVarFormParams.Add("file_name", this.Configuration.ApiClient.ParameterToString(fileName)); // form parameter
            if (videoFile != null) localVarFileParams.Add("video_file", this.Configuration.ApiClient.ParameterToFile("video_file", videoFile));
            if (audioFile != null) localVarFileParams.Add("audio_file", this.Configuration.ApiClient.ParameterToFile("audio_file", audioFile));
            if (imageFile != null) localVarFileParams.Add("image_file", this.Configuration.ApiClient.ParameterToFile("image_file", imageFile));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// upload shows upload shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> UploadShowsAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile)
        {
             ApiResponse<string> localVarResponse = await UploadShowsAsyncWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId, fileName, videoFile, audioFile, imageFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// upload shows upload shows
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <param name="fileName">user login ,only support wechat</param>
        /// <param name="videoFile">user login ,only support wechat</param>
        /// <param name="audioFile">user login ,only support wechat</param>
        /// <param name="imageFile">user login ,only support wechat</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> UploadShowsAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId, string fileName, System.IO.Stream videoFile, System.IO.Stream audioFile, System.IO.Stream imageFile)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling ShowsApi->UploadShows");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling ShowsApi->UploadShows");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ShowsApi->UploadShows");
            // verify the required parameter 'fileName' is set
            if (fileName == null)
                throw new ApiException(400, "Missing required parameter 'fileName' when calling ShowsApi->UploadShows");
            // verify the required parameter 'videoFile' is set
            if (videoFile == null)
                throw new ApiException(400, "Missing required parameter 'videoFile' when calling ShowsApi->UploadShows");
            // verify the required parameter 'audioFile' is set
            if (audioFile == null)
                throw new ApiException(400, "Missing required parameter 'audioFile' when calling ShowsApi->UploadShows");
            // verify the required parameter 'imageFile' is set
            if (imageFile == null)
                throw new ApiException(400, "Missing required parameter 'imageFile' when calling ShowsApi->UploadShows");

            var localVarPath = "/user/{user_id}/uploaded_shows";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (fileName != null) localVarFormParams.Add("file_name", this.Configuration.ApiClient.ParameterToString(fileName)); // form parameter
            if (videoFile != null) localVarFileParams.Add("video_file", this.Configuration.ApiClient.ParameterToFile("video_file", videoFile));
            if (audioFile != null) localVarFileParams.Add("audio_file", this.Configuration.ApiClient.ParameterToFile("audio_file", audioFile));
            if (imageFile != null) localVarFileParams.Add("image_file", this.Configuration.ApiClient.ParameterToFile("image_file", imageFile));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UploadShows", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
