/* 
 * appServer
 *
 * AppServer openApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bing.he@ihandysoft
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>LoginResponse</returns>
        LoginResponse GetUserProfile (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId);

        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of LoginResponse</returns>
        ApiResponse<LoginResponse> GetUserProfileWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId);
        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>string</returns>
        string PutUserProfile (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null);

        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> PutUserProfileWithHttpInfo (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null);
        /// <summary>
        /// UserLogin
        /// </summary>
        /// <remarks>
        /// user login
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>LoginResponse</returns>
        LoginResponse Userlogin (string xColorPhoneSignature, LoginRequest body);

        /// <summary>
        /// UserLogin
        /// </summary>
        /// <remarks>
        /// user login
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>ApiResponse of LoginResponse</returns>
        ApiResponse<LoginResponse> UserloginWithHttpInfo (string xColorPhoneSignature, LoginRequest body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>Task of LoginResponse</returns>
        System.Threading.Tasks.Task<LoginResponse> GetUserProfileAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId);

        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>Task of ApiResponse (LoginResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginResponse>> GetUserProfileAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId);
        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> PutUserProfileAsync (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null);

        /// <summary>
        /// UserProfile
        /// </summary>
        /// <remarks>
        /// UserProfile
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> PutUserProfileAsyncWithHttpInfo (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null);
        /// <summary>
        /// UserLogin
        /// </summary>
        /// <remarks>
        /// user login
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>Task of LoginResponse</returns>
        System.Threading.Tasks.Task<LoginResponse> UserloginAsync (string xColorPhoneSignature, LoginRequest body);

        /// <summary>
        /// UserLogin
        /// </summary>
        /// <remarks>
        /// user login
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>Task of ApiResponse (LoginResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginResponse>> UserloginAsyncWithHttpInfo (string xColorPhoneSignature, LoginRequest body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserApi : IUserApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>LoginResponse</returns>
        public LoginResponse GetUserProfile (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId)
        {
             ApiResponse<LoginResponse> localVarResponse = GetUserProfileWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of LoginResponse</returns>
        public ApiResponse< LoginResponse > GetUserProfileWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling UserApi->GetUserProfile");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling UserApi->GetUserProfile");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UserApi->GetUserProfile");

            var localVarPath = "/user/{user_id}/profile";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserProfile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LoginResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LoginResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LoginResponse)));
        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>Task of LoginResponse</returns>
        public async System.Threading.Tasks.Task<LoginResponse> GetUserProfileAsync (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId)
        {
             ApiResponse<LoginResponse> localVarResponse = await GetUserProfileAsyncWithHttpInfo(xColorPhoneSessionToken, xColorPhoneSignature, userId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSessionToken">Token</param>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="userId"></param>
        /// <returns>Task of ApiResponse (LoginResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LoginResponse>> GetUserProfileAsyncWithHttpInfo (string xColorPhoneSessionToken, string xColorPhoneSignature, string userId)
        {
            // verify the required parameter 'xColorPhoneSessionToken' is set
            if (xColorPhoneSessionToken == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSessionToken' when calling UserApi->GetUserProfile");
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling UserApi->GetUserProfile");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UserApi->GetUserProfile");

            var localVarPath = "/user/{user_id}/profile";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserProfile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LoginResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LoginResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LoginResponse)));
        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>string</returns>
        public string PutUserProfile (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null)
        {
             ApiResponse<string> localVarResponse = PutUserProfileWithHttpInfo(userId, name, gender, birthday, signature, headImage, xColorPhoneSessionToken, xColorPhoneSignature);
             return localVarResponse.Data;
        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > PutUserProfileWithHttpInfo (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UserApi->PutUserProfile");
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling UserApi->PutUserProfile");
            // verify the required parameter 'gender' is set
            if (gender == null)
                throw new ApiException(400, "Missing required parameter 'gender' when calling UserApi->PutUserProfile");
            // verify the required parameter 'birthday' is set
            if (birthday == null)
                throw new ApiException(400, "Missing required parameter 'birthday' when calling UserApi->PutUserProfile");
            // verify the required parameter 'signature' is set
            if (signature == null)
                throw new ApiException(400, "Missing required parameter 'signature' when calling UserApi->PutUserProfile");
            // verify the required parameter 'headImage' is set
            if (headImage == null)
                throw new ApiException(400, "Missing required parameter 'headImage' when calling UserApi->PutUserProfile");

            var localVarPath = "/user/{user_id}/profile";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (name != null) localVarFormParams.Add("name", this.Configuration.ApiClient.ParameterToString(name)); // form parameter
            if (gender != null) localVarFormParams.Add("gender", this.Configuration.ApiClient.ParameterToString(gender)); // form parameter
            if (birthday != null) localVarFormParams.Add("birthday", this.Configuration.ApiClient.ParameterToString(birthday)); // form parameter
            if (signature != null) localVarFormParams.Add("signature", this.Configuration.ApiClient.ParameterToString(signature)); // form parameter
            if (headImage != null) localVarFileParams.Add("head_image", this.Configuration.ApiClient.ParameterToFile("head_image", headImage));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutUserProfile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> PutUserProfileAsync (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null)
        {
             ApiResponse<string> localVarResponse = await PutUserProfileAsyncWithHttpInfo(userId, name, gender, birthday, signature, headImage, xColorPhoneSessionToken, xColorPhoneSignature);
             return localVarResponse.Data;

        }

        /// <summary>
        /// UserProfile UserProfile
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="name">user login ,only support wechat</param>
        /// <param name="gender">user login ,only support wechat</param>
        /// <param name="birthday">user login ,only support wechat</param>
        /// <param name="signature">user login ,only support wechat</param>
        /// <param name="headImage">user login ,only support wechat</param>
        /// <param name="xColorPhoneSessionToken">Token (optional)</param>
        /// <param name="xColorPhoneSignature">Signature (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> PutUserProfileAsyncWithHttpInfo (string userId, string name, string gender, string birthday, string signature, System.IO.Stream headImage, string xColorPhoneSessionToken = null, string xColorPhoneSignature = null)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling UserApi->PutUserProfile");
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling UserApi->PutUserProfile");
            // verify the required parameter 'gender' is set
            if (gender == null)
                throw new ApiException(400, "Missing required parameter 'gender' when calling UserApi->PutUserProfile");
            // verify the required parameter 'birthday' is set
            if (birthday == null)
                throw new ApiException(400, "Missing required parameter 'birthday' when calling UserApi->PutUserProfile");
            // verify the required parameter 'signature' is set
            if (signature == null)
                throw new ApiException(400, "Missing required parameter 'signature' when calling UserApi->PutUserProfile");
            // verify the required parameter 'headImage' is set
            if (headImage == null)
                throw new ApiException(400, "Missing required parameter 'headImage' when calling UserApi->PutUserProfile");

            var localVarPath = "/user/{user_id}/profile";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("user_id", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (xColorPhoneSessionToken != null) localVarHeaderParams.Add("X-ColorPhone-Session-Token", this.Configuration.ApiClient.ParameterToString(xColorPhoneSessionToken)); // header parameter
            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (name != null) localVarFormParams.Add("name", this.Configuration.ApiClient.ParameterToString(name)); // form parameter
            if (gender != null) localVarFormParams.Add("gender", this.Configuration.ApiClient.ParameterToString(gender)); // form parameter
            if (birthday != null) localVarFormParams.Add("birthday", this.Configuration.ApiClient.ParameterToString(birthday)); // form parameter
            if (signature != null) localVarFormParams.Add("signature", this.Configuration.ApiClient.ParameterToString(signature)); // form parameter
            if (headImage != null) localVarFileParams.Add("head_image", this.Configuration.ApiClient.ParameterToFile("head_image", headImage));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutUserProfile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// UserLogin user login
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>LoginResponse</returns>
        public LoginResponse Userlogin (string xColorPhoneSignature, LoginRequest body)
        {
             ApiResponse<LoginResponse> localVarResponse = UserloginWithHttpInfo(xColorPhoneSignature, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// UserLogin user login
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>ApiResponse of LoginResponse</returns>
        public ApiResponse< LoginResponse > UserloginWithHttpInfo (string xColorPhoneSignature, LoginRequest body)
        {
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling UserApi->Userlogin");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling UserApi->Userlogin");

            var localVarPath = "/user/login";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Userlogin", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LoginResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LoginResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LoginResponse)));
        }

        /// <summary>
        /// UserLogin user login
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>Task of LoginResponse</returns>
        public async System.Threading.Tasks.Task<LoginResponse> UserloginAsync (string xColorPhoneSignature, LoginRequest body)
        {
             ApiResponse<LoginResponse> localVarResponse = await UserloginAsyncWithHttpInfo(xColorPhoneSignature, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// UserLogin user login
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xColorPhoneSignature">Signature</param>
        /// <param name="body">user login ,only support wechat</param>
        /// <returns>Task of ApiResponse (LoginResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LoginResponse>> UserloginAsyncWithHttpInfo (string xColorPhoneSignature, LoginRequest body)
        {
            // verify the required parameter 'xColorPhoneSignature' is set
            if (xColorPhoneSignature == null)
                throw new ApiException(400, "Missing required parameter 'xColorPhoneSignature' when calling UserApi->Userlogin");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling UserApi->Userlogin");

            var localVarPath = "/user/login";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xColorPhoneSignature != null) localVarHeaderParams.Add("X-ColorPhone-Signature", this.Configuration.ApiClient.ParameterToString(xColorPhoneSignature)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Userlogin", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LoginResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LoginResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LoginResponse)));
        }

    }
}
